### ISSUE TITLE
[기능설계]Streamlit 데모 실행 테스트

### ISSUE THREAD

**Issue by in-sukim** [in-sukim/SNAP_ver2#6]
## 설명📄
- 전체 프로세스 시간 단축 방법 모색 및 Streamlit 적용.

## To-Do✅
- [] 비동기처리 적용을 통해 전체 프로세스 소요시간 단축
- [] ffmpeg 영상 구간 편집 적용
- [] Streamlit 적용하여 데모 테스트

## 기타사항
기타 사항을 작성해주세요.
